### ISSUE TITLE
on-giving-up callback broken

### ISSUE THREAD

**Issue by rikumalminiemi** [Enrise/ng-poll-img#1]
Hi,

on-giving-up callback seems to be broken. I have defined callback function and I reference it like this:  on-giving-up="giveUp()". If I use same function with on-success everything works fine.

**Comment by rskuipers** [comment]
@rikup88 Thank you for reporting this, I have reproduced the issue and will look into it :)

**Comment by rskuipers** [comment]
@rikup88 Fixed in 2.0.1
